### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by travc** [alimanfoo/vcfnp#49]
Might be a problem on my end, but in case it isn't...
It looks like there is something odd with the way `vcflib` is linked as a submodule in `vcfnp`

```
$ git clone -v --recursive git://github.com/alimanfoo/vcfnp.git 
...normal stuff...
Submodule 'vcflib' (git@github.com:alimanfoo/vcflib.git) registered for path 'vcflib'
Cloning into 'vcflib'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

If I clone (recursively) your repo of `vcflib` by hand within the `vcfnp` directory, it seem to work fine.  So I'm thinking that something is wrong with the submodule link.

**Comment by alimanfoo** [comment]
Thanks Travis, I've verified this happens to me when logged in as a different user. I'll try to find a fix.

**Comment by alimanfoo** [comment]
Hi Travis, have you configured an SSH key with your GitHub account? If you have, the following should work:

```
$ git clone -v --recursive git@github.com:alimanfoo/vcfnp.git
```

If not, that will fail with permission denied at the very beginning (i.e., before getting to the submodules).

**Comment by travc** [comment]
That's the problem.  I've been using submodules (even have some in my own repos) and never seen that issue before.  Odd, but easily fixed.
