### ISSUE TITLE
bug generating hdf5 from vcf

### ISSUE THREAD

**Issue by travc** [alimanfoo/vcfnp#54]
There is a bug when generating hdf5 from vcf...  
When vcflib (via htslib) gets a VariantCallFile iterator for a region, it will include variants which have a position before the region start if their length 'overlaps' the region.  Eg: a len 5 del at pos 97 will be included in the output for region chr:100.

This can cause duplicates when .npy files for regions are collected into an hdf5.  It can even cause non-monotonic POS values in cases like:
98 len 5 del
99 snp
101 snp
if the regions were chr:1-100 and chr:101-200

The behavior of vcflib isn't really wrong, so these cases should be handled at a higher level.  The simple way is to just trim off any variants which have a POS value < the region start.  I'm not sure where would be best place to put that test though.  I'll poke around some more myself, though I suspect you probably have an idea where to put the fix.

**Comment by alimanfoo** [comment]
Just pushed a fix. Now by default variants should be truncated to region, however user can override with `truncate` keyword argument.
