### ISSUE TITLE
EFF Amino_Acid_Change field being truncated

### ISSUE THREAD

**Issue by travc** [alimanfoo/vcfnp#62]
EFF `Amino_Acid_Change` field is truncated on long transcripts (>10000 residues) since it is dtype `a6`.

Changing it at the top of `eff.py` where you define `EFF_DEFAULT_DTYPE` to something larger (I'd suggest `a8` to be safe and even) should fix the problem, at least for SNPs.  I'm checking now but will probably sleep before it is done.

I should probably be using ANN, but having the single-letter AA residue to residue mapping right there is just too convenient for my current task.

**Comment by alimanfoo** [comment]
Thanks Travis, I'll change default to 'a8'.

**Comment by alimanfoo** [comment]
Changed via #58.
