### ISSUE TITLE
vcfnp.variants abbreviates strings in CHROM column

### ISSUE THREAD

**Issue by alexhbnr** [alimanfoo/vcfnp#65]
vcfnp.variants behaves strangely, when parsing the VCF into a NumPy array and cuts the length of the CHROM field so that it ends up to be at max. 12 characters.

In general, this should not be a problem, but in my specific case my sequencing data was aligned to multiple individual genes of bacterial genomes with multiple contigs. In order to identify these genes correctly the name of "CHROM" fields got rather long, sometimes up to 18 characters. Instead of returning the full string all "CHROM" names are trim to 12 characters when importing it into Python using vcfnp.

For example, I would expect "aact1954_c_16_1574" but get instead "aact1954_c_1". This is problematic in a way that the 12-character string is not unique across the VCF file and, when doing analysis per "CHROM", I end up merging "CHROM"s that would be separated when considering the full string.

Is this abbreviation expected?

**Comment by alimanfoo** [comment]
Hi Alex,

You can customise the dtype for any field by passing in a ``dtypes`` keyword argument. E.g.:

```python
v = vcfnp.variants('example.vcf', dtypes={'CHROM': 'S18'})
```

There are predefined default dtypes for various fields including CHROM which you may need to customise.

If you're using the command line tool there is a similar option to specify a custom dtype.

Hth.

**Comment by alexhbnr** [comment]
Thanks, Alistair, for the very quick reply and the great solution. Works smoothly!

**Comment by alimanfoo** [comment]
No problem!
